In [3]:
import pandas as pd

df = pd.read_csv('salaries_by_college_major.csv')

clean_df = df.dropna()

clean_df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [70]:
# Use .head(), .tail(), .shape and .columns to explore your DataFrame and find out the number of rows and columns as well as the column names.

clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [5]:
clean_df.shape

(50, 6)

In [6]:
clean_df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [71]:
# Look for NaN (not a number) values with .findna() and consider using .dropna() to clean up your DataFrame.

clean_df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False

In [72]:
# You can access entire columns of a DataFrame using the square bracket notation:
# df['column name'] or df[['column name 1', 'column name 2', 'column name 3']]

clean_df['Undergraduate Major']

0                               Accounting
1                    Aerospace Engineering
2                              Agriculture
3                             Anthropology
4                             Architecture
5                              Art History
6                                  Biology
7                      Business Management
8                     Chemical Engineering
9                                Chemistry
10                       Civil Engineering
11                          Communications
12                    Computer Engineering
13                        Computer Science
14                            Construction
15                        Criminal Justice
16                                   Drama
17                               Economics
18                               Education
19                  Electrical Engineering
20                                 English
21                                    Film
22                                 Finance
23                                Forestry
24                               Geography
25                                 Geology
26                          Graphic Design
27              Health Care Administration
28                                 History
29                   Hospitality & Tourism
30                  Industrial Engineering
31             Information Technology (IT)
32                         Interior Design
33                 International Relations
34                              Journalism
35    Management Information Systems (MIS)
36                               Marketing
37                                    Math
38                  Mechanical Engineering
39                                   Music
40                                 Nursing
41                               Nutrition
42                              Philosophy
43                     Physician Assistant
44                                 Physics
45                       Political Science
46                              Psychology
47                                Religion
48                               Sociology
49                                 Spanish
Name: Undergraduate Major, dtype: object

In [16]:
clean_df[['Undergraduate Major', 'Starting Median Salary', 'Mid-Career Median Salary']]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary
0,Accounting,46000.0,77100.0
1,Aerospace Engineering,57700.0,101000.0
2,Agriculture,42600.0,71900.0
3,Anthropology,36800.0,61500.0
4,Architecture,41600.0,76800.0
5,Art History,35800.0,64900.0
6,Biology,38800.0,64800.0
7,Business Management,43000.0,72100.0
8,Chemical Engineering,63200.0,107000.0
9,Chemistry,42600.0,79900.0
10,Civil Engineering,53900.0,90500.0
11,Communications,38100.0,70000.0
12,Computer Engineering,61400.0,105000.0
13,Computer Science,55900.0,95500.0
14,Construction,53700.0,88900.0
15,Criminal Justice,35000.0,56300.0
16,Drama,35900.0,56900.0
17,Economics,50100.0,98600.0
18,Education,34900.0,52000.0
19,Electrical Engineering,60900.0,103000.0
20,English,38000.0,64700.0
21,Film,37900.0,68500.0
22,Finance,47900.0,88300.0
23,Forestry,39100.0,62600.0
24,Geography,41200.0,65500.0
25,Geology,43500.0,79500.0
26,Graphic Design,35700.0,59800.0
27,Health Care Administration,38800.0,60600.0
28,History,39200.0,71000.0
29,Hospitality & Tourism,37800.0,57500.0
30,Industrial Engineering,57700.0,94700.0
31,Information Technology (IT),49100.0,74800.0
32,Interior Design,36100.0,53200.0
33,International Relations,40900.0,80900.0
34,Journalism,35600.0,66700.0
35,Management Information Systems (MIS),49200.0,82300.0
36,Marketing,40800.0,79600.0
37,Math,45400.0,92400.0
38,Mechanical Engineering,57900.0,93600.0
39,Music,35900.0,55000.0
40,Nursing,54200.0,67000.0
41,Nutrition,39900.0,55300.0
42,Philosophy,39900.0,81200.0
43,Physician Assistant,74300.0,91700.0
44,Physics,50300.0,97300.0
45,Political Science,40800.0,78200.0
46,Psychology,35900.0,60400.0
47,Religion,34100.0,52000.0
48,Sociology,36500.0,58200.0
49,Spanish,34000.0,53100.0

In [73]:
# You can access individual cells in a DataFrame by chaining square brackets df['column name'][index] or using df['column name'].loc[index]

clean_df['Undergraduate Major'][5]

'Art History'

In [18]:
clean_df.loc[3]

Undergraduate Major                  Anthropology
Starting Median Salary                    36800.0
Mid-Career Median Salary                  61500.0
Mid-Career 10th Percentile Salary         33800.0
Mid-Career 90th Percentile Salary        138000.0
Group                                        HASS
Name: 3, dtype: object

In [74]:
# The largest and smallest values, as well as their positions, can be found with methods like .max(), .min(), .idxmax() and .idxmin()

clean_df.max()

Undergraduate Major                   Spanish
Starting Median Salary                74300.0
Mid-Career Median Salary             107000.0
Mid-Career 10th Percentile Salary     71900.0
Mid-Career 90th Percentile Salary    210000.0
Group                                    STEM
dtype: object

In [20]:
clean_df.min()

Undergraduate Major                  Accounting
Starting Median Salary                  34000.0
Mid-Career Median Salary                52000.0
Mid-Career 10th Percentile Salary       26700.0
Mid-Career 90th Percentile Salary       96400.0
Group                                  Business
dtype: object

In [27]:
clean_df['Starting Median Salary'].idxmax()

43

In [28]:
clean_df['Mid-Career 10th Percentile Salary'].idxmin()

39

In [75]:
# You can sort the DataFrame with .sort_values() and add new columns with .insert()
# ps: Come back and learn this part again

nova = {'Col1':[1,2,3]}

clean_df.insert(1, 'mais', nova)

In [57]:
clean_df.head()

,Undergraduate Major,mais,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,NaN,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,NaN,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,NaN,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,NaN,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,NaN,41600.0,76800.0,50600.0,136000.0,Business

In [76]:
del clean_df["mais"] # To delete a column

In [59]:
clean_df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [66]:
clean_df.sort_values('Starting Median Salary')

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
20,English,38000.0,64700.0,33400.0,133000.0,HASS
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM

In [77]:
# To create an Excel Style Pivot Table by grouping entries that belong to a particular category use the .groupby() method

clean_df.groupby('Group').count()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,12,12,12,12,12
HASS,22,22,22,22,22
STEM,16,16,16,16,16